version: "3.4"
services:
  app:
    build: 
      context: docker/
    command: /bin/sleep infinity
    working_dir: /usr/src/
    volumes:
      - "../:/usr/src:cached"
    expose:
      - "80"
    environment:
      - DNSDOCK_ALIAS=app.${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - VIRTUAL_HOST=app.${PROJECT_NAME}.${PROJECT_VENDOR}.docker
      - VIRTUAL_PORT=80
